/* Generated By:JJTree: Do not edit this line. ASTArithmetic.java */

package pcgen.base.formula.parse;

public class ASTArithmetic extends SimpleNode {
  public ASTArithmetic(int id) {
    super(id);
  }

  public ASTArithmetic(FormulaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FormulaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
