/* Generated By:JJTree: Do not edit this line. ASTExpon.java */

package pcgen.base.formula.parse;

public class ASTExpon extends SimpleNode {
  public ASTExpon(int id) {
    super(id);
  }

  public ASTExpon(FormulaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FormulaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
