/* Generated By:JJTree: Do not edit this line. ASTEquality.java */

package pcgen.base.formula.parse;

public class ASTEquality extends SimpleNode {
  public ASTEquality(int id) {
    super(id);
  }

  public ASTEquality(FormulaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FormulaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
