/* Generated By:JJTree: Do not edit this line. ASTFParen.java */

package pcgen.base.formula.parse;

public class ASTFParen extends SimpleNode {
  public ASTFParen(int id) {
    super(id);
  }

  public ASTFParen(FormulaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FormulaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
