/* Generated By:JJTree: Do not edit this line. ASTLogical.java */

package pcgen.base.formula.parse;

public class ASTLogical extends SimpleNode {
  public ASTLogical(int id) {
    super(id);
  }

  public ASTLogical(FormulaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FormulaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
