/* Generated By:JJTree: Do not edit this line. ASTPCGenSingleWord.java */

package pcgen.base.formula.parse;

public class ASTPCGenSingleWord extends SimpleNode {
  public ASTPCGenSingleWord(int id) {
    super(id);
  }

  public ASTPCGenSingleWord(FormulaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FormulaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
