/* Generated By:JJTree: Do not edit this line. ASTPCGenLookup.java */

package pcgen.base.formula.parse;

public class ASTPCGenLookup extends SimpleNode {
  public ASTPCGenLookup(int id) {
    super(id);
  }

  public ASTPCGenLookup(FormulaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FormulaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
