/* Generated By:JJTree: Do not edit this line. ASTParen.java */

package pcgen.base.formula.parse;

public class ASTParen extends SimpleNode {
  public ASTParen(int id) {
    super(id);
  }

  public ASTParen(FormulaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FormulaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
