/* Generated By:JJTree: Do not edit this line. ASTPCGenBracket.java */

package pcgen.base.formula.parse;

public class ASTPCGenBracket extends SimpleNode {
  public ASTPCGenBracket(int id) {
    super(id);
  }

  public ASTPCGenBracket(FormulaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FormulaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
