/* Generated By:JJTree: Do not edit this line. ASTRelational.java */

package pcgen.base.formula.parse;

public class ASTRelational extends SimpleNode {
  public ASTRelational(int id) {
    super(id);
  }

  public ASTRelational(FormulaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FormulaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
