/* Generated By:JJTree: Do not edit this line. C:\Users\Tom\workspace-bonus\PCGenFormulaParser\src\main\java\pcgen\base\formula\parse\FormulaParserTreeConstants.java */

package pcgen.base.formula.parse;

public interface FormulaParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTLOGICAL = 2;
  public int JJTEQUALITY = 3;
  public int JJTRELATIONAL = 4;
  public int JJTARITHMETIC = 5;
  public int JJTGEOMETRIC = 6;
  public int JJTUNARY = 7;
  public int JJTEXPON = 8;
  public int JJTPAREN = 9;
  public int JJTNUM = 10;
  public int JJTPCGENLOOKUP = 11;
  public int JJTPCGENSINGLEWORD = 12;
  public int JJTPCGENBRACKET = 13;
  public int JJTFPAREN = 14;
  public int JJTQUOTSTRING = 15;


  public String[] jjtNodeName = {
    "Root",
    "void",
    "Logical",
    "Equality",
    "Relational",
    "Arithmetic",
    "Geometric",
    "Unary",
    "Expon",
    "Paren",
    "Num",
    "PCGenLookup",
    "PCGenSingleWord",
    "PCGenBracket",
    "FParen",
    "QuotString",
  };
}
