/* Generated By:JJTree&JavaCC: Do not edit this line. FormulaParserConstants.java */
package pcgen.base.formula.parse;

public interface FormulaParserConstants {

  int EOF = 0;
  int PERCENT = 1;
  int COLON = 2;
  int HYPHEN = 3;
  int SOLIDUS = 4;
  int EQUALSIGN = 5;
  int UNDERSCORE = 6;
  int TILDE = 7;
  int SPACE = 8;
  int O_SPACE = 9;
  int PLUS = 10;
  int MINUS = 11;
  int MULT = 12;
  int DIV = 13;
  int REM = 14;
  int POW = 15;
  int COMMA = 16;
  int OPENPAREN = 17;
  int CLOSEPAREN = 18;
  int OPENBRACKET = 19;
  int CLOSEBRACKET = 20;
  int GT = 21;
  int LT = 22;
  int GTEQ = 23;
  int LTEQ = 24;
  int EQUAL = 25;
  int NOTEQUAL = 26;
  int AND = 27;
  int OR = 28;
  int FULLSTOP = 29;
  int DIGIT = 30;
  int BASIC_LETTER = 31;
  int FINAL_LETTER = 32;
  int MID_LETTER = 33;
  int VARIABLE = 34;
  int INT = 35;
  int STRING_FORBIDDEN = 36;
  int STRING_ESCAPED = 37;
  int STRING_LITERAL = 38;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"%\"",
    "\":\"",
    "\"-\"",
    "\"/\"",
    "\"=\"",
    "\"_\"",
    "\"~\"",
    "\" \"",
    "<O_SPACE>",
    "<PLUS>",
    "<MINUS>",
    "<MULT>",
    "<DIV>",
    "<REM>",
    "<POW>",
    "<COMMA>",
    "<OPENPAREN>",
    "<CLOSEPAREN>",
    "<OPENBRACKET>",
    "<CLOSEBRACKET>",
    "<GT>",
    "<LT>",
    "<GTEQ>",
    "<LTEQ>",
    "<EQUAL>",
    "<NOTEQUAL>",
    "<AND>",
    "<OR>",
    "\".\"",
    "<DIGIT>",
    "<BASIC_LETTER>",
    "<FINAL_LETTER>",
    "<MID_LETTER>",
    "<VARIABLE>",
    "<INT>",
    "<STRING_FORBIDDEN>",
    "<STRING_ESCAPED>",
    "<STRING_LITERAL>",
  };

}
