/* Generated By:JJTree&JavaCC: Do not edit this line. FormulaParserTokenManager.java */
package pcgen.base.formula.parse;

public class FormulaParserTokenManager implements FormulaParserConstants
{
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private final int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private final int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private final int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 46:
         return jjStopAtPos(0, 29);
      default :
         return jjMoveNfa_0(44, 0);
   }
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0x1ff00000fffffffeL, 0xffffffffffffc000L, 0xffffffffL, 0x600000000000000L
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0x0L, 0xff7fffffff7fffffL
};
static final long[] jjbitVec3 = {
   0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec4 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffL, 0x0L
};
static final long[] jjbitVec5 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0x0L, 0x0L
};
static final long[] jjbitVec6 = {
   0x3fffffffffffL, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec7 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec8 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 78;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 44:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                  }
                  else if (curChar == 34)
                     jjCheckNAddStates(0, 2);
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 35)
                        kind = 35;
                     jjCheckNAdd(49);
                  }
                  else if (curChar == 32)
                     jjCheckNAddStates(3, 40);
                  else if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 38;
                  else if (curChar == 33)
                     jjstateSet[jjnewStateCnt++] = 35;
                  else if (curChar == 61)
                     jjstateSet[jjnewStateCnt++] = 32;
                  else if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 29;
                  else if (curChar == 62)
                     jjstateSet[jjnewStateCnt++] = 26;
                  else if (curChar == 41)
                  {
                     if (kind > 18)
                        kind = 18;
                     jjCheckNAdd(17);
                  }
                  else if (curChar == 40)
                  {
                     if (kind > 17)
                        kind = 17;
                     jjCheckNAdd(15);
                  }
                  else if (curChar == 44)
                  {
                     if (kind > 16)
                        kind = 16;
                     jjCheckNAdd(13);
                  }
                  else if (curChar == 37)
                  {
                     if (kind > 14)
                        kind = 14;
                     jjCheckNAdd(9);
                  }
                  else if (curChar == 47)
                  {
                     if (kind > 13)
                        kind = 13;
                     jjCheckNAdd(7);
                  }
                  else if (curChar == 42)
                  {
                     if (kind > 12)
                        kind = 12;
                     jjCheckNAdd(5);
                  }
                  else if (curChar == 45)
                  {
                     if (kind > 11)
                        kind = 11;
                     jjCheckNAdd(3);
                  }
                  else if (curChar == 43)
                  {
                     if (kind > 10)
                        kind = 10;
                     jjCheckNAdd(1);
                  }
                  if (curChar == 60)
                  {
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAdd(25);
                  }
                  else if (curChar == 62)
                  {
                     if (kind > 21)
                        kind = 21;
                     jjCheckNAdd(23);
                  }
                  break;
               case 0:
                  if (curChar != 43)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(1);
                  break;
               case 1:
                  if (curChar != 32)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(1);
                  break;
               case 2:
                  if (curChar != 45)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAdd(3);
                  break;
               case 3:
                  if (curChar != 32)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAdd(3);
                  break;
               case 4:
                  if (curChar != 42)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(5);
                  break;
               case 5:
                  if (curChar != 32)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(5);
                  break;
               case 6:
                  if (curChar != 47)
                     break;
                  if (kind > 13)
                     kind = 13;
                  jjCheckNAdd(7);
                  break;
               case 7:
                  if (curChar != 32)
                     break;
                  if (kind > 13)
                     kind = 13;
                  jjCheckNAdd(7);
                  break;
               case 8:
                  if (curChar != 37)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAdd(9);
                  break;
               case 9:
                  if (curChar != 32)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAdd(9);
                  break;
               case 11:
                  if (curChar != 32)
                     break;
                  if (kind > 15)
                     kind = 15;
                  jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 12:
                  if (curChar != 44)
                     break;
                  if (kind > 16)
                     kind = 16;
                  jjCheckNAdd(13);
                  break;
               case 13:
                  if (curChar != 32)
                     break;
                  if (kind > 16)
                     kind = 16;
                  jjCheckNAdd(13);
                  break;
               case 14:
                  if (curChar != 40)
                     break;
                  if (kind > 17)
                     kind = 17;
                  jjCheckNAdd(15);
                  break;
               case 15:
                  if (curChar != 32)
                     break;
                  if (kind > 17)
                     kind = 17;
                  jjCheckNAdd(15);
                  break;
               case 16:
                  if (curChar != 41)
                     break;
                  if (kind > 18)
                     kind = 18;
                  jjCheckNAdd(17);
                  break;
               case 17:
                  if (curChar != 32)
                     break;
                  if (kind > 18)
                     kind = 18;
                  jjCheckNAdd(17);
                  break;
               case 19:
                  if (curChar != 32)
                     break;
                  if (kind > 19)
                     kind = 19;
                  jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar != 32)
                     break;
                  if (kind > 20)
                     kind = 20;
                  jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 22:
                  if (curChar != 62)
                     break;
                  if (kind > 21)
                     kind = 21;
                  jjCheckNAdd(23);
                  break;
               case 23:
                  if (curChar != 32)
                     break;
                  if (kind > 21)
                     kind = 21;
                  jjCheckNAdd(23);
                  break;
               case 24:
                  if (curChar != 60)
                     break;
                  if (kind > 22)
                     kind = 22;
                  jjCheckNAdd(25);
                  break;
               case 25:
                  if (curChar != 32)
                     break;
                  if (kind > 22)
                     kind = 22;
                  jjCheckNAdd(25);
                  break;
               case 26:
                  if (curChar != 61)
                     break;
                  if (kind > 23)
                     kind = 23;
                  jjCheckNAdd(27);
                  break;
               case 27:
                  if (curChar != 32)
                     break;
                  if (kind > 23)
                     kind = 23;
                  jjCheckNAdd(27);
                  break;
               case 28:
                  if (curChar == 62)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 29:
                  if (curChar != 61)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAdd(30);
                  break;
               case 30:
                  if (curChar != 32)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAdd(30);
                  break;
               case 31:
                  if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 32:
                  if (curChar != 61)
                     break;
                  if (kind > 25)
                     kind = 25;
                  jjCheckNAdd(33);
                  break;
               case 33:
                  if (curChar != 32)
                     break;
                  if (kind > 25)
                     kind = 25;
                  jjCheckNAdd(33);
                  break;
               case 34:
                  if (curChar == 61)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 35:
                  if (curChar != 61)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAdd(36);
                  break;
               case 36:
                  if (curChar != 32)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAdd(36);
                  break;
               case 37:
                  if (curChar == 33)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 38:
                  if (curChar != 38)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAdd(39);
                  break;
               case 39:
                  if (curChar != 32)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAdd(39);
                  break;
               case 40:
                  if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 42:
                  if (curChar != 32)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 45:
                  if ((0x7ff402100000000L & l) != 0L)
                     jjCheckNAddStates(41, 43);
                  break;
               case 46:
                  if (curChar == 61)
                     jjCheckNAddTwoStates(47, 48);
                  break;
               case 47:
                  if ((0x7ff402100000000L & l) != 0L)
                     jjCheckNAddTwoStates(47, 48);
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) != 0L && kind > 34)
                     kind = 34;
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 35)
                     kind = 35;
                  jjCheckNAdd(49);
                  break;
               case 50:
                  if ((0xfffffffbffffdbffL & l) != 0L && kind > 36)
                     kind = 36;
                  break;
               case 52:
                  if ((0x8400000000L & l) != 0L && kind > 37)
                     kind = 37;
                  break;
               case 53:
                  if (curChar == 34)
                     jjCheckNAddStates(0, 2);
                  break;
               case 54:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 56:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 57:
                  if (curChar == 34 && kind > 38)
                     kind = 38;
                  break;
               case 58:
                  if (curChar == 32)
                     jjCheckNAddStates(3, 40);
                  break;
               case 59:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(59, 0);
                  break;
               case 60:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(60, 2);
                  break;
               case 61:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(61, 4);
                  break;
               case 62:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(62, 6);
                  break;
               case 63:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(63, 8);
                  break;
               case 64:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(64, 10);
                  break;
               case 65:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(65, 12);
                  break;
               case 66:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(66, 14);
                  break;
               case 67:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(67, 16);
                  break;
               case 68:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(68, 18);
                  break;
               case 69:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(69, 20);
                  break;
               case 70:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(70, 22);
                  break;
               case 71:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(71, 24);
                  break;
               case 72:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(72, 28);
                  break;
               case 73:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(73, 31);
                  break;
               case 74:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(74, 34);
                  break;
               case 75:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(75, 37);
                  break;
               case 76:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(76, 40);
                  break;
               case 77:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(77, 43);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 44:
                  if ((0xffffffffefffffffL & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                  }
                  else if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 52;
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 34)
                        kind = 34;
                     jjCheckNAddStates(41, 43);
                  }
                  else if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 41;
                  else if (curChar == 93)
                  {
                     if (kind > 20)
                        kind = 20;
                     jjstateSet[jjnewStateCnt++] = 21;
                  }
                  else if (curChar == 91)
                  {
                     if (kind > 19)
                        kind = 19;
                     jjstateSet[jjnewStateCnt++] = 19;
                  }
                  else if (curChar == 94)
                  {
                     if (kind > 15)
                        kind = 15;
                     jjstateSet[jjnewStateCnt++] = 11;
                  }
                  break;
               case 10:
                  if (curChar != 94)
                     break;
                  if (kind > 15)
                     kind = 15;
                  jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 18:
                  if (curChar != 91)
                     break;
                  if (kind > 19)
                     kind = 19;
                  jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 20:
                  if (curChar != 93)
                     break;
                  if (kind > 20)
                     kind = 20;
                  jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 41:
                  if (curChar != 124)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 43:
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 45:
                  if ((0x47fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(41, 43);
                  break;
               case 47:
                  if ((0x47fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(47, 48);
                  break;
               case 48:
                  if ((0x47fffffe07fffffeL & l) != 0L && kind > 34)
                     kind = 34;
                  break;
               case 50:
                  if ((0xffffffffefffffffL & l) != 0L && kind > 36)
                     kind = 36;
                  break;
               case 51:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 52:
                  if ((0x14404410000000L & l) != 0L && kind > 37)
                     kind = 37;
                  break;
               case 54:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 55:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 56:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 44:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 34)
                        kind = 34;
                     jjCheckNAddStates(41, 43);
                  }
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 36)
                        kind = 36;
                  }
                  break;
               case 45:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(41, 43);
                  break;
               case 47:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(47, 48);
                  break;
               case 48:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 34)
                     kind = 34;
                  break;
               case 50:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2) && kind > 36)
                     kind = 36;
                  break;
               case 54:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     jjAddStates(0, 2);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 78 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   54, 55, 57, 59, 0, 60, 2, 61, 4, 62, 6, 63, 8, 64, 10, 65, 
   12, 66, 14, 67, 16, 68, 18, 69, 20, 70, 22, 71, 24, 72, 28, 73, 
   31, 74, 34, 75, 37, 76, 40, 77, 43, 45, 46, 48, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      case 48:
         return ((jjbitVec3[i2] & l2) != 0L);
      case 49:
         return ((jjbitVec4[i2] & l2) != 0L);
      case 51:
         return ((jjbitVec5[i2] & l2) != 0L);
      case 61:
         return ((jjbitVec6[i2] & l2) != 0L);
      default : 
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}
private static final boolean jjCanMove_1(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec8[i2] & l2) != 0L);
      default : 
         if ((jjbitVec7[i1] & l1) != 0L)
            return true;
         return false;
   }
}
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, "\56", null, null, null, null, null, null, null, null, null, };
public static final String[] lexStateNames = {
   "DEFAULT", 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[78];
private final int[] jjstateSet = new int[156];
protected char curChar;
public FormulaParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public FormulaParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 78; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
         matchedToken = jjFillToken();
         return matchedToken;
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

}
