/* Generated By:JJTree&JavaCC: Do not edit this line. FormulaParser.java */
package pcgen.base.formula.parse;

public class FormulaParser/*@bgen(jjtree)*/implements FormulaParserTreeConstants, FormulaParserConstants {/*@bgen(jjtree)*/
  protected JJTFormulaParserState jjtree = new JJTFormulaParserState();

  final public SimpleNode query() throws ParseException {
                              /*@bgen(jjtree) Root */
  ASTRoot jjtn000 = new ASTRoot(JJTROOT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MINUS:
      case REM:
      case OPENPAREN:
      case FULLSTOP:
      case VARIABLE:
      case INT:
        logicalExpr();
        break;
      default:
        jj_la1[0] = jj_gen;
        ;
      }
      jj_consume_token(0);
                  jjtree.closeNodeScope(jjtn000, true);
                  jjtc000 = false;
                  {if (true) return jjtn000;}
    } catch (Throwable jjte000) {
                  if (jjtc000) {
                    jjtree.clearNodeScope(jjtn000);
                    jjtc000 = false;
                  } else {
                    jjtree.popNode();
                  }
                  if (jjte000 instanceof RuntimeException) {
                    {if (true) throw (RuntimeException)jjte000;}
                  }
                  if (jjte000 instanceof ParseException) {
                    {if (true) throw (ParseException)jjte000;}
                  }
                  {if (true) throw (Error)jjte000;}
    } finally {
                  if (jjtc000) {
                    jjtree.closeNodeScope(jjtn000, true);
                  }
    }
    throw new Error("Missing return statement in function");
  }

/******************************************************************************
 * Add Logical expression and function
 *****************************************************************************/
  final public void logicalExpr() throws ParseException {
                               Operator image;
    equalityExpr();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
      case OR:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
      image = logicalFtn();
                                               ASTLogical jjtn001 = new ASTLogical(JJTLOGICAL);
                                               boolean jjtc001 = true;
                                               jjtree.openNodeScope(jjtn001);
      try {
        equalityExpr();
      } catch (Throwable jjte001) {
                                               if (jjtc001) {
                                                 jjtree.clearNodeScope(jjtn001);
                                                 jjtc001 = false;
                                               } else {
                                                 jjtree.popNode();
                                               }
                                               if (jjte001 instanceof RuntimeException) {
                                                 {if (true) throw (RuntimeException)jjte001;}
                                               }
                                               if (jjte001 instanceof ParseException) {
                                                 {if (true) throw (ParseException)jjte001;}
                                               }
                                               {if (true) throw (Error)jjte001;}
      } finally {
                                               if (jjtc001) {
                                                 jjtree.closeNodeScope(jjtn001,  2);
                                               }
      }
                          ((SimpleNode) jjtree.peekNode()).setOperator(image);
    }
  }

  final public Operator logicalFtn() throws ParseException {
                                  Operator image;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OR:
      image = orToken();
      break;
    case AND:
      image = andToken();
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                  {if (true) return image;}
    throw new Error("Missing return statement in function");
  }

  final public Operator orToken() throws ParseException {
    jj_consume_token(OR);
                  {if (true) return Operator.OR;}
    throw new Error("Missing return statement in function");
  }

  final public Operator andToken() throws ParseException {
    jj_consume_token(AND);
                  {if (true) return Operator.AND;}
    throw new Error("Missing return statement in function");
  }

/******************************************************************************
 * Add Equality expression and functions
 *****************************************************************************/
  final public void equalityExpr() throws ParseException {
                                Operator image;
    relationalExpr();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQUAL:
      case NOTEQUAL:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
      image = equalityFtn();
                                                ASTEquality jjtn001 = new ASTEquality(JJTEQUALITY);
                                                boolean jjtc001 = true;
                                                jjtree.openNodeScope(jjtn001);
      try {
        relationalExpr();
      } catch (Throwable jjte001) {
                                                if (jjtc001) {
                                                  jjtree.clearNodeScope(jjtn001);
                                                  jjtc001 = false;
                                                } else {
                                                  jjtree.popNode();
                                                }
                                                if (jjte001 instanceof RuntimeException) {
                                                  {if (true) throw (RuntimeException)jjte001;}
                                                }
                                                if (jjte001 instanceof ParseException) {
                                                  {if (true) throw (ParseException)jjte001;}
                                                }
                                                {if (true) throw (Error)jjte001;}
      } finally {
                                                if (jjtc001) {
                                                  jjtree.closeNodeScope(jjtn001,  2);
                                                }
      }
                          ((SimpleNode) jjtree.peekNode()).setOperator(image);
    }
  }

  final public Operator equalityFtn() throws ParseException {
                                   Operator image;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQUAL:
      image = equalToken();
      break;
    case NOTEQUAL:
      image = notEqualToken();
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                  {if (true) return image;}
    throw new Error("Missing return statement in function");
  }

  final public Operator equalToken() throws ParseException {
    jj_consume_token(EQUAL);
                  {if (true) return Operator.EQ;}
    throw new Error("Missing return statement in function");
  }

  final public Operator notEqualToken() throws ParseException {
    jj_consume_token(NOTEQUAL);
                  {if (true) return Operator.NEQ;}
    throw new Error("Missing return statement in function");
  }

/******************************************************************************
 * Add Relational expression and functions
 *****************************************************************************/
  final public void relationalExpr() throws ParseException {
                                  Operator image;
    arithmeticExpr();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case GT:
      case LT:
      case GTEQ:
      case LTEQ:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_3;
      }
      image = relationalFtn();
                                                  ASTRelational jjtn001 = new ASTRelational(JJTRELATIONAL);
                                                  boolean jjtc001 = true;
                                                  jjtree.openNodeScope(jjtn001);
      try {
        arithmeticExpr();
      } catch (Throwable jjte001) {
                                                  if (jjtc001) {
                                                    jjtree.clearNodeScope(jjtn001);
                                                    jjtc001 = false;
                                                  } else {
                                                    jjtree.popNode();
                                                  }
                                                  if (jjte001 instanceof RuntimeException) {
                                                    {if (true) throw (RuntimeException)jjte001;}
                                                  }
                                                  if (jjte001 instanceof ParseException) {
                                                    {if (true) throw (ParseException)jjte001;}
                                                  }
                                                  {if (true) throw (Error)jjte001;}
      } finally {
                                                  if (jjtc001) {
                                                    jjtree.closeNodeScope(jjtn001,  2);
                                                  }
      }
                          ((SimpleNode) jjtree.peekNode()).setOperator(image);
    }
  }

  final public Operator relationalFtn() throws ParseException {
                                     Operator image;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LT:
      image = lessThanToken();
      break;
    case GT:
      image = greaterThanToken();
      break;
    case LTEQ:
      image = lessThanOrEqualToToken();
      break;
    case GTEQ:
      image = greaterThanOrEqualToToken();
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                  {if (true) return image;}
    throw new Error("Missing return statement in function");
  }

  final public Operator lessThanToken() throws ParseException {
    jj_consume_token(LT);
                  {if (true) return Operator.LT;}
    throw new Error("Missing return statement in function");
  }

  final public Operator greaterThanToken() throws ParseException {
    jj_consume_token(GT);
                  {if (true) return Operator.GT;}
    throw new Error("Missing return statement in function");
  }

  final public Operator lessThanOrEqualToToken() throws ParseException {
    jj_consume_token(LTEQ);
                  {if (true) return Operator.LE;}
    throw new Error("Missing return statement in function");
  }

  final public Operator greaterThanOrEqualToToken() throws ParseException {
    jj_consume_token(GTEQ);
                  {if (true) return Operator.GE;}
    throw new Error("Missing return statement in function");
  }

/******************************************************************************
 * Add Arithmetic expression and function - addition and subtraction have
 * equal precedence
 *****************************************************************************/
  final public void arithmeticExpr() throws ParseException {
                                  Operator image;
    geometricExpr();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
      case MINUS:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_4;
      }
      image = arithmeticFtn();
                                                  ASTArithmetic jjtn001 = new ASTArithmetic(JJTARITHMETIC);
                                                  boolean jjtc001 = true;
                                                  jjtree.openNodeScope(jjtn001);
      try {
        geometricExpr();
      } catch (Throwable jjte001) {
                                                  if (jjtc001) {
                                                    jjtree.clearNodeScope(jjtn001);
                                                    jjtc001 = false;
                                                  } else {
                                                    jjtree.popNode();
                                                  }
                                                  if (jjte001 instanceof RuntimeException) {
                                                    {if (true) throw (RuntimeException)jjte001;}
                                                  }
                                                  if (jjte001 instanceof ParseException) {
                                                    {if (true) throw (ParseException)jjte001;}
                                                  }
                                                  {if (true) throw (Error)jjte001;}
      } finally {
                                                  if (jjtc001) {
                                                    jjtree.closeNodeScope(jjtn001,  2);
                                                  }
      }
                          ((SimpleNode) jjtree.peekNode()).setOperator(image);
    }
  }

  final public Operator arithmeticFtn() throws ParseException {
                                     Operator image;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PLUS:
      image = plusToken();
      break;
    case MINUS:
      image = minusToken();
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                  {if (true) return image;}
    throw new Error("Missing return statement in function");
  }

  final public Operator plusToken() throws ParseException {
    jj_consume_token(PLUS);
                  {if (true) return Operator.ADD;}
    throw new Error("Missing return statement in function");
  }

  final public Operator minusToken() throws ParseException {
    jj_consume_token(MINUS);
                  {if (true) return Operator.SUB;}
    throw new Error("Missing return statement in function");
  }

/******************************************************************************
 * Add Geometric expression and functions - multiplication and both types of
 * division have equal precedence
 *****************************************************************************/
  final public void geometricExpr() throws ParseException {
                                 Operator image;
    unaryExpr();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULT:
      case DIV:
      case REM:
        ;
        break;
      default:
        jj_la1[9] = jj_gen;
        break label_5;
      }
      image = geometricFtn();
                                                 ASTGeometric jjtn001 = new ASTGeometric(JJTGEOMETRIC);
                                                 boolean jjtc001 = true;
                                                 jjtree.openNodeScope(jjtn001);
      try {
        unaryExpr();
      } catch (Throwable jjte001) {
                                                 if (jjtc001) {
                                                   jjtree.clearNodeScope(jjtn001);
                                                   jjtc001 = false;
                                                 } else {
                                                   jjtree.popNode();
                                                 }
                                                 if (jjte001 instanceof RuntimeException) {
                                                   {if (true) throw (RuntimeException)jjte001;}
                                                 }
                                                 if (jjte001 instanceof ParseException) {
                                                   {if (true) throw (ParseException)jjte001;}
                                                 }
                                                 {if (true) throw (Error)jjte001;}
      } finally {
                                                 if (jjtc001) {
                                                   jjtree.closeNodeScope(jjtn001,  2);
                                                 }
      }
                          ((SimpleNode) jjtree.peekNode()).setOperator(image);
    }
  }

  final public Operator geometricFtn() throws ParseException {
                                    Operator image;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MULT:
      image = multToken();
      break;
    case DIV:
      image = divToken();
      break;
    case REM:
      image = remToken();
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                  {if (true) return image;}
    throw new Error("Missing return statement in function");
  }

  final public Operator multToken() throws ParseException {
    jj_consume_token(MULT);
                  {if (true) return Operator.MUL;}
    throw new Error("Missing return statement in function");
  }

  final public Operator divToken() throws ParseException {
    jj_consume_token(DIV);
                  {if (true) return Operator.DIV;}
    throw new Error("Missing return statement in function");
  }

  final public Operator remToken() throws ParseException {
    jj_consume_token(REM);
                  {if (true) return Operator.REM;}
    throw new Error("Missing return statement in function");
  }

/******************************************************************************
 * Add Unary expression
 *****************************************************************************/
  final public void unaryExpr() throws ParseException {
                             Token t = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MINUS:
      t = jj_consume_token(MINUS);
      break;
    default:
      jj_la1[11] = jj_gen;
      ;
    }
                                 ASTUnary jjtn001 = new ASTUnary(JJTUNARY);
                                 boolean jjtc001 = true;
                                 jjtree.openNodeScope(jjtn001);
    try {
      exponExpr();
    } catch (Throwable jjte001) {
                                 if (jjtc001) {
                                   jjtree.clearNodeScope(jjtn001);
                                   jjtc001 = false;
                                 } else {
                                   jjtree.popNode();
                                 }
                                 if (jjte001 instanceof RuntimeException) {
                                   {if (true) throw (RuntimeException)jjte001;}
                                 }
                                 if (jjte001 instanceof ParseException) {
                                   {if (true) throw (ParseException)jjte001;}
                                 }
                                 {if (true) throw (Error)jjte001;}
    } finally {
                                 if (jjtc001) {
                                   jjtree.closeNodeScope(jjtn001,  t != null);
                                 }
    }
  }

/******************************************************************************
 * Add Exponential expression
 *****************************************************************************/
  final public void exponExpr() throws ParseException {
                                 /*@bgen(jjtree) #Expon(> 1) */
  ASTExpon jjtn000 = new ASTExpon(JJTEXPON);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      primitiveExpr();
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case POW:
          ;
          break;
        default:
          jj_la1[12] = jj_gen;
          break label_6;
        }
        jj_consume_token(POW);
        primitiveExpr();
                                jjtn000.setOperator(Operator.EXP);
      }
    } catch (Throwable jjte000) {
                  if (jjtc000) {
                    jjtree.clearNodeScope(jjtn000);
                    jjtc000 = false;
                  } else {
                    jjtree.popNode();
                  }
                  if (jjte000 instanceof RuntimeException) {
                    {if (true) throw (RuntimeException)jjte000;}
                  }
                  if (jjte000 instanceof ParseException) {
                    {if (true) throw (ParseException)jjte000;}
                  }
                  {if (true) throw (Error)jjte000;}
    } finally {
                  if (jjtc000) {
                    jjtree.closeNodeScope(jjtn000, jjtree.nodeArity() > 1);
                  }
    }
  }

/******************************************************************************
 * Now we're at the productions that will form the leaves of the tree
 *****************************************************************************/
  final public void primitiveExpr() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OPENPAREN:
      parenExpr();
      break;
    case FULLSTOP:
    case INT:
      numberExpr();
      break;
    case REM:
    case VARIABLE:
      lookupExpr();
      break;
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void parenExpr() throws ParseException {
                             /*@bgen(jjtree) Paren */
  ASTParen jjtn000 = new ASTParen(JJTPAREN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(OPENPAREN);
      logicalExpr();
      jj_consume_token(CLOSEPAREN);
    } catch (Throwable jjte000) {
                  if (jjtc000) {
                    jjtree.clearNodeScope(jjtn000);
                    jjtc000 = false;
                  } else {
                    jjtree.popNode();
                  }
                  if (jjte000 instanceof RuntimeException) {
                    {if (true) throw (RuntimeException)jjte000;}
                  }
                  if (jjte000 instanceof ParseException) {
                    {if (true) throw (ParseException)jjte000;}
                  }
                  {if (true) throw (Error)jjte000;}
    } finally {
                  if (jjtc000) {
                    jjtree.closeNodeScope(jjtn000, true);
                  }
    }
  }

  final public void numberExpr() throws ParseException {
                            /*@bgen(jjtree) Num */
                 ASTNum jjtn000 = new ASTNum(JJTNUM);
                 boolean jjtc000 = true;
                 jjtree.openNodeScope(jjtn000);Token t1 = null, t2 = null, t3 = null;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INT:
        t1 = jj_consume_token(INT);
        if (jj_2_1(2)) {
          t2 = jj_consume_token(FULLSTOP);
          t3 = jj_consume_token(INT);
        } else {
          ;
        }
        break;
      case FULLSTOP:
        t1 = jj_consume_token(FULLSTOP);
        t2 = jj_consume_token(INT);
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                  jjtree.closeNodeScope(jjtn000, true);
                  jjtc000 = false;
                        String image;
                        if (t3 == null) {
                                if (t2 == null) {
                                        image = t1.image;
                                } else {
                                        image = "." + t2.image;
                                }
                        } else {
                                image = t1.image + "." + t3.image;
                        }
                        jjtn000.setToken(image);
    } finally {
                  if (jjtc000) {
                    jjtree.closeNodeScope(jjtn000, true);
                  }
    }
  }

/******************************************************************************
 * This is the start of the PCGEN specific stuff.  The "Dot separated words"
 * are used for our OS tokens and in some of our predefined variables.
 *****************************************************************************/
  final public void lookupExpr() throws ParseException {
                                        /*@bgen(jjtree) #PCGenLookup(> 1) */
  ASTPCGenLookup jjtn000 = new ASTPCGenLookup(JJTPCGENLOOKUP);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      pcgenSingleWord();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OPENPAREN:
      case OPENBRACKET:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case OPENBRACKET:
          pcgenBracketGroup();
          break;
        case OPENPAREN:
          parenGroup();
          break;
        default:
          jj_la1[15] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[16] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
                  if (jjtc000) {
                    jjtree.clearNodeScope(jjtn000);
                    jjtc000 = false;
                  } else {
                    jjtree.popNode();
                  }
                  if (jjte000 instanceof RuntimeException) {
                    {if (true) throw (RuntimeException)jjte000;}
                  }
                  if (jjte000 instanceof ParseException) {
                    {if (true) throw (ParseException)jjte000;}
                  }
                  {if (true) throw (Error)jjte000;}
    } finally {
                  if (jjtc000) {
                    jjtree.closeNodeScope(jjtn000, jjtree.nodeArity() > 1);
                  }
    }
  }

  final public void pcgenSingleWord() throws ParseException {
                                             /*@bgen(jjtree) PCGenSingleWord */
                             ASTPCGenSingleWord jjtn000 = new ASTPCGenSingleWord(JJTPCGENSINGLEWORD);
                             boolean jjtc000 = true;
                             jjtree.openNodeScope(jjtn000);Token t; Token i = null;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case REM:
        i = jj_consume_token(REM);
        break;
      default:
        jj_la1[17] = jj_gen;
        ;
      }
      t = jj_consume_token(VARIABLE);
                  jjtree.closeNodeScope(jjtn000, true);
                  jjtc000 = false;
                        String image;
                        if (i == null) {
                                image = t.image;
                        } else {
                            if (i.image.lastIndexOf(" ") == i.image.length() - 1)
                            {
                                {if (true) throw new ParseException("Found Word with embedded space: " + i.image + t.image);}
                            }
                                image = i.image + t.image;
                        }
                        /*
			 * Cannot enforce spaces on other words, due to Class names allowing spaces
			 */
                        jjtn000.setToken(image);
    } finally {
                  if (jjtc000) {
                    jjtree.closeNodeScope(jjtn000, true);
                  }
    }
  }

  final public void pcgenBracketGroup() throws ParseException {
                                            /*@bgen(jjtree) PCGenBracket */
  ASTPCGenBracket jjtn000 = new ASTPCGenBracket(JJTPCGENBRACKET);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(OPENBRACKET);
      pcgenSingleWord();
      jj_consume_token(CLOSEBRACKET);
    } catch (Throwable jjte000) {
                  if (jjtc000) {
                    jjtree.clearNodeScope(jjtn000);
                    jjtc000 = false;
                  } else {
                    jjtree.popNode();
                  }
                  if (jjte000 instanceof RuntimeException) {
                    {if (true) throw (RuntimeException)jjte000;}
                  }
                  if (jjte000 instanceof ParseException) {
                    {if (true) throw (ParseException)jjte000;}
                  }
                  {if (true) throw (Error)jjte000;}
    } finally {
                  if (jjtc000) {
                    jjtree.closeNodeScope(jjtn000, true);
                  }
    }
  }

  final public void parenGroup() throws ParseException {
                               /*@bgen(jjtree) FParen */
                    ASTFParen jjtn000 = new ASTFParen(JJTFPAREN);
                    boolean jjtc000 = true;
                    jjtree.openNodeScope(jjtn000);Token t1;
    try {
      jj_consume_token(OPENPAREN);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MINUS:
      case REM:
      case OPENPAREN:
      case FULLSTOP:
      case VARIABLE:
      case INT:
      case STRING_LITERAL:
        functionExpr();
        label_7:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case COMMA:
            ;
            break;
          default:
            jj_la1[18] = jj_gen;
            break label_7;
          }
          jj_consume_token(COMMA);
          functionExpr();
        }
        break;
      default:
        jj_la1[19] = jj_gen;
        ;
      }
      jj_consume_token(CLOSEPAREN);
    } catch (Throwable jjte000) {
                  if (jjtc000) {
                    jjtree.clearNodeScope(jjtn000);
                    jjtc000 = false;
                  } else {
                    jjtree.popNode();
                  }
                  if (jjte000 instanceof RuntimeException) {
                    {if (true) throw (RuntimeException)jjte000;}
                  }
                  if (jjte000 instanceof ParseException) {
                    {if (true) throw (ParseException)jjte000;}
                  }
                  {if (true) throw (Error)jjte000;}
    } finally {
                  if (jjtc000) {
                    jjtree.closeNodeScope(jjtn000, true);
                  }
    }
  }

  final public void functionExpr() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MINUS:
    case REM:
    case OPENPAREN:
    case FULLSTOP:
    case VARIABLE:
    case INT:
      logicalExpr();
      break;
    case STRING_LITERAL:
      quotedString();
      break;
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void quotedString() throws ParseException {
                                     /*@bgen(jjtree) QuotString */
                        ASTQuotString jjtn000 = new ASTQuotString(JJTQUOTSTRING);
                        boolean jjtc000 = true;
                        jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(STRING_LITERAL);
                  jjtree.closeNodeScope(jjtn000, true);
                  jjtc000 = false;
                        String stripped = t.image.substring(1, t.image.length() - 1);
                        jjtn000.setToken(stripped);
    } finally {
                  if (jjtc000) {
                    jjtree.closeNodeScope(jjtn000, true);
                  }
    }
  }

  final private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  final private boolean jj_3_1() {
    if (jj_scan_token(FULLSTOP)) return true;
    if (jj_scan_token(INT)) return true;
    return false;
  }

  public FormulaParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  public Token token, jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  public boolean lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[21];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_0();
      jj_la1_1();
   }
   private static void jj_la1_0() {
      jj_la1_0 = new int[] {0x20024800,0x18000000,0x18000000,0x6000000,0x6000000,0x1e00000,0x1e00000,0xc00,0xc00,0x7000,0x7000,0x800,0x8000,0x20024000,0x20000000,0xa0000,0xa0000,0x4000,0x10000,0x20024800,0x20024800,};
   }
   private static void jj_la1_1() {
      jj_la1_1 = new int[] {0xc,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xc,0x8,0x0,0x0,0x0,0x0,0x4c,0x4c,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[1];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  public FormulaParser(java.io.InputStream stream) {
     this(stream, null);
  }
  public FormulaParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new FormulaParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public FormulaParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new FormulaParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public FormulaParser(FormulaParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(FormulaParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  final private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  final private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }

  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  final public Token getToken(int index) {
    Token t = lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  final private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.Vector jj_expentries = new java.util.Vector();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Enumeration e = jj_expentries.elements(); e.hasMoreElements();) {
        int[] oldentry = (int[])(e.nextElement());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.addElement(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  public ParseException generateParseException() {
    jj_expentries.removeAllElements();
    boolean[] la1tokens = new boolean[39];
    for (int i = 0; i < 39; i++) {
      la1tokens[i] = false;
    }
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 21; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 39; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.addElement(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.elementAt(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  final public void enable_tracing() {
  }

  final public void disable_tracing() {
  }

  final private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 1; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  final private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
